module.exports = {
  INSERT: `INSERT INTO AVISOS (ID_AVISO, ID_PERSONA, ID_CITA, MENSAJE, FECHA_AVISO) VALUES ($1, $2, $3, $4, $5)`,
  SELECT_ALL: `SELECT * FROM AVISOS`,
  SELECT_BY_ID: `SELECT * FROM AVISOS WHERE ID_AVISO = $1`,
  DELETE: `DELETE FROM AVISOS WHERE ID_AVISO = $1`,
  UPDATE: `UPDATE AVISOS SET ID_PERSONA = $1, ID_CITA = $2, MENSAJE = $3, FECHA_AVISO = $4 WHERE ID_AVISO = $5`,
  SELECT_BY_PERSONA: `SELECT * FROM AVISOS WHERE ID_PERSONA = $1`,
  SELECT_BY_PERSONA_CITA_MENSAJE_POSTGRES: `SELECT * FROM AVISOS WHERE ID_PERSONA = $1 AND ID_CITA = $2 AND MENSAJE = $3`
};

