// sql/postgres/usuario.sql.js
module.exports = {
  INSERT: `INSERT INTO USUARIOS (ID_USUARIO, NOMBRE, CORREO, TELEFONO, PASSWORD, NOMBRE_EMPRESA, FOTO) VALUES ($1, $2, $3, $4, $5, $6, $7)`,
  SELECT_BY_CORREO: `SELECT * FROM USUARIOS WHERE CORREO = $1`,
  SELECT_ALL: `SELECT * FROM USUARIOS`
};
